sudo: required
services:
    - docker

before_install:
    - docker build -t nikeshkamble25/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true nikeshkamble25/docker-react npm run test

deploy:
    provider: azure_web_apps
    username: nikeshk@quinnox.com         # If AZURE_WA_USERNAME isn't set
    password: Truist@12                   # If AZURE_WA_PASSWORD isn't set
    site: react-container-code             # If AZURE_WA_SITE isn't set